import { Module } from "./types";

export const modules: Module[] = [
  {
    moduleId: "pe-foundations",
    moduleTitle: "Private Equity Foundations",
    description:
      "A 20-day curriculum building PE fluency from fund structure to portfolio construction. Designed for CFA charterholders with public-markets backgrounds.",
    lessons: [
      {
        lessonId: "day-01",
        dayNumber: 1,
        title: "How Private Equity Actually Works",
        estimatedMinutes: 45,
        topics: ["pe-basics", "fund-structure", "capital-flow"],
        difficulty: "foundational",
        prerequisites: [],
        learningObjectives: [
          "Explain the basic PE fund model in plain English",
          "Understand how capital is called, invested, harvested, and distributed",
          "Distinguish GP-level claims from fund-structure mechanics",
        ],
      },
      {
        lessonId: "day-02",
        dayNumber: 2,
        title: "GPs, LPs, and the Incentive Stack",
        estimatedMinutes: 43,
        topics: ["gp-lp", "incentives", "carried-interest"],
        difficulty: "foundational",
        prerequisites: ["day-01"],
        learningObjectives: [
          "Understand the GP/LP relationship",
          "Explain management fees and carried interest",
          "Describe how incentive alignment works in PE",
        ],
      },
      {
        lessonId: "day-03",
        dayNumber: 3,
        title: "Capital Calls and the J-Curve",
        estimatedMinutes: 40,
        topics: ["capital-calls", "j-curve", "cash-flows"],
        difficulty: "foundational",
        prerequisites: ["day-01", "day-02"],
        learningObjectives: [
          "Explain the capital call mechanism",
          "Understand the J-curve and why it happens",
          "Anticipate liquidity implications for LPs",
        ],
      },
      {
        lessonId: "day-04",
        dayNumber: 4,
        title: "IRR: What It Measures and Where It Breaks",
        estimatedMinutes: 48,
        topics: ["irr", "performance-measurement"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-03"],
        learningObjectives: [
          "Calculate and interpret IRR",
          "Identify where IRR is gamed or misleading",
          "Distinguish gross from net IRR",
        ],
      },
      {
        lessonId: "day-05",
        dayNumber: 5,
        title: "TVPI, DPI, and RVPI Explained",
        estimatedMinutes: 42,
        topics: ["tvpi", "dpi", "rvpi", "performance-measurement"],
        difficulty: "intermediate",
        prerequisites: ["day-04"],
        learningObjectives: [
          "Define TVPI, DPI, and RVPI",
          "Understand how they relate to each other",
          "Use multiples alongside IRR for a complete picture",
        ],
      },
      {
        lessonId: "day-06",
        dayNumber: 6,
        title: "Fund Life Cycles and Vintage Years",
        estimatedMinutes: 38,
        topics: ["fund-lifecycle", "vintage-year", "benchmarking"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-03"],
        learningObjectives: [
          "Interpret any PE fund's metrics correctly by lifecycle phase",
          "Explain why vintage year is the primary benchmarking axis",
          "Construct a valid vintage-adjusted peer group comparison",
          "Identify what metrics are informative at each lifecycle stage",
        ],
      },
      {
        lessonId: "day-07",
        dayNumber: 7,
        title: "Buyout Strategy Fundamentals",
        estimatedMinutes: 43,
        topics: ["buyout", "leverage", "deal-structure", "return-attribution"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-02"],
        learningObjectives: [
          "Apply the five deal selection criteria for buyout targets",
          "Explain capital structure design and leverage amplification arithmetic",
          "Decompose LBO returns into the three-driver value bridge",
          "Interrogate a GP's value creation claims using deal-level attribution",
        ],
      },
      {
        lessonId: "day-08",
        dayNumber: 8,
        title: "Growth Equity vs. Buyout vs. Venture",
        estimatedMinutes: 42,
        topics: ["growth-equity", "buyout", "venture", "portfolio-construction", "strategy-drift"],
        difficulty: "intermediate",
        prerequisites: ["day-07"],
        learningObjectives: [
          "Compare buyout, growth equity, and VC across six analytical dimensions",
          "Explain the portfolio construction role of each sub-strategy",
          "Recognize strategy drift before it becomes a governance problem",
          "Apply sub-strategy-appropriate benchmarks and J-curve expectations",
        ],
      },
      {
        lessonId: "day-09",
        dayNumber: 9,
        title: "Value Creation in PE Portfolio Companies",
        estimatedMinutes: 45,
        topics: ["value-creation", "operations", "portfolio-companies", "return-attribution"],
        difficulty: "intermediate",
        prerequisites: ["day-07"],
        learningObjectives: [
          "Distinguish the four forms of EBITDA growth and their repeatability",
          "Audit a GP's operational value creation claim using portfolio-level data",
          "Identify red flags in value creation presentations",
          "Assess operating partner substance versus marketing",
        ],
      },
      {
        lessonId: "day-10",
        dayNumber: 10,
        title: "Exit Paths: Trade Sales, IPOs, and Secondaries",
        estimatedMinutes: 42,
        topics: ["exits", "ipo", "secondary-buyout", "irr-moic-tradeoff"],
        difficulty: "intermediate",
        prerequisites: ["day-07", "day-09"],
        learningObjectives: [
          "Explain the mechanics and valuation dynamics of each exit route",
          "Quantify the IRR/MOIC trade-off in exit timing decisions",
          "Read secondary buyout patterns as a portfolio quality signal",
          "Analyze a GP's historical exit pattern as a diligence input",
        ],
      },
      {
        lessonId: "day-11",
        dayNumber: 11,
        title: "Fund Terms: What to Negotiate",
        estimatedMinutes: 25,
        topics: ["fund-terms", "lpa", "gp-lp"],
        difficulty: "intermediate",
        prerequisites: ["day-02"],
        learningObjectives: [
          "Identify key terms in a limited partnership agreement",
          "Understand economic and governance provisions",
          "Know what institutional LPs typically negotiate",
        ],
      },
      {
        lessonId: "day-12",
        dayNumber: 12,
        title: "Manager Selection and Due Diligence",
        estimatedMinutes: 30,
        topics: ["manager-selection", "due-diligence"],
        difficulty: "advanced",
        prerequisites: ["day-04", "day-05", "day-11"],
        learningObjectives: [
          "Build a PE manager evaluation framework",
          "Distinguish luck from skill in track records",
          "Ask better questions in manager meetings",
        ],
      },
      {
        lessonId: "day-13",
        dayNumber: 13,
        title: "Benchmarking PE Performance",
        estimatedMinutes: 25,
        topics: ["benchmarking", "pme", "performance-measurement"],
        difficulty: "advanced",
        prerequisites: ["day-04", "day-05", "day-06"],
        learningObjectives: [
          "Use PME to compare PE to public markets",
          "Understand benchmark construction issues",
          "Avoid common performance attribution errors",
        ],
      },
      {
        lessonId: "day-14",
        dayNumber: 14,
        title: "Portfolio Construction and Pacing",
        estimatedMinutes: 25,
        topics: ["pacing", "portfolio-construction", "allocation"],
        difficulty: "advanced",
        prerequisites: ["day-06", "day-13"],
        learningObjectives: [
          "Design a pacing model for PE allocations",
          "Manage vintage year diversification",
          "Balance commitment pacing with liquidity needs",
        ],
      },
      {
        lessonId: "day-15",
        dayNumber: 15,
        title: "Secondaries: Liquidity and Opportunity",
        estimatedMinutes: 20,
        topics: ["secondary", "liquidity", "gp-led"],
        difficulty: "advanced",
        prerequisites: ["day-10", "day-14"],
        learningObjectives: [
          "Explain the secondary market structure",
          "Distinguish LP-led from GP-led secondaries",
          "Evaluate continuation vehicles and NAV financing",
        ],
      },
      {
        lessonId: "day-16",
        dayNumber: 16,
        title: "Co-investments: Structure and Risks",
        estimatedMinutes: 20,
        topics: ["co-investment", "deal-structure"],
        difficulty: "advanced",
        prerequisites: ["day-07", "day-12"],
        learningObjectives: [
          "Explain how co-investments work",
          "Assess adverse selection risk",
          "Understand fee economics for LPs",
        ],
      },
      {
        lessonId: "day-17",
        dayNumber: 17,
        title: "PE as an Asset Class: Allocation Frameworks",
        estimatedMinutes: 25,
        topics: ["asset-allocation", "portfolio-construction"],
        difficulty: "advanced",
        prerequisites: ["day-14"],
        learningObjectives: [
          "Position PE within a broader portfolio",
          "Understand illiquidity premium arguments",
          "Apply an allocator lens to PE sizing",
        ],
      },
      {
        lessonId: "day-18",
        dayNumber: 18,
        title: "Reporting, NAV, and Mark-to-Market",
        estimatedMinutes: 20,
        topics: ["reporting", "nav", "valuation"],
        difficulty: "advanced",
        prerequisites: ["day-05", "day-09"],
        learningObjectives: [
          "Understand how NAV is calculated and reported",
          "Recognize smoothing effects and their implications",
          "Evaluate GP reporting quality",
        ],
      },
      {
        lessonId: "day-19",
        dayNumber: 19,
        title: "ESG, Impact, and New Pressures on PE",
        estimatedMinutes: 20,
        topics: ["esg", "impact", "regulation"],
        difficulty: "intermediate",
        prerequisites: ["day-12"],
        learningObjectives: [
          "Describe ESG integration in PE",
          "Distinguish impact investing from ESG",
          "Understand regulatory and LP pressure on GPs",
        ],
      },
      {
        lessonId: "day-20",
        dayNumber: 20,
        title: "PE Fluency: Putting It All Together",
        estimatedMinutes: 30,
        topics: [
          "synthesis",
          "meeting-fluency",
          "allocator-thinking",
        ],
        difficulty: "advanced",
        prerequisites: ["day-19"],
        learningObjectives: [
          "Synthesize the full 20-day curriculum",
          "Apply PE fluency in a manager meeting context",
          "Identify areas for ongoing development",
        ],
      },
    ],
  },
];

export function getModuleById(moduleId: string): Module | undefined {
  return modules.find((m) => m.moduleId === moduleId);
}
