import { Module } from "./types";

export const modules: Module[] = [
  {
    moduleId: "pe-foundations",
    moduleTitle: "Private Equity Foundations",
    description:
      "A 36-day curriculum building PE fluency from fund structure through venture capital mechanics, covering fund economics, benchmarking, manager selection, programme construction, fund governance, and VC portfolio analysis. Designed for CFA charterholders with public-markets backgrounds.",
    lessons: [
      {
        lessonId: "day-01",
        dayNumber: 1,
        title: "How Private Equity Actually Works",
        estimatedMinutes: 45,
        topics: ["pe-basics", "fund-structure", "capital-flow"],
        difficulty: "foundational",
        prerequisites: [],
        learningObjectives: [
          "Explain the basic PE fund model in plain English",
          "Understand how capital is called, invested, harvested, and distributed",
          "Distinguish GP-level claims from fund-structure mechanics",
        ],
      },
      {
        lessonId: "day-02",
        dayNumber: 2,
        title: "GPs, LPs, and the Incentive Stack",
        estimatedMinutes: 43,
        topics: ["gp-lp", "incentives", "carried-interest"],
        difficulty: "foundational",
        prerequisites: ["day-01"],
        learningObjectives: [
          "Understand the GP/LP relationship",
          "Explain management fees and carried interest",
          "Describe how incentive alignment works in PE",
        ],
      },
      {
        lessonId: "day-03",
        dayNumber: 3,
        title: "Capital Calls and the J-Curve",
        estimatedMinutes: 40,
        topics: ["capital-calls", "j-curve", "cash-flows"],
        difficulty: "foundational",
        prerequisites: ["day-01", "day-02"],
        learningObjectives: [
          "Explain the capital call mechanism",
          "Understand the J-curve and why it happens",
          "Anticipate liquidity implications for LPs",
        ],
      },
      {
        lessonId: "day-04",
        dayNumber: 4,
        title: "IRR: What It Measures and Where It Breaks",
        estimatedMinutes: 48,
        topics: ["irr", "performance-measurement"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-03"],
        learningObjectives: [
          "Calculate and interpret IRR",
          "Identify where IRR is gamed or misleading",
          "Distinguish gross from net IRR",
        ],
      },
      {
        lessonId: "day-05",
        dayNumber: 5,
        title: "TVPI, DPI, and RVPI Explained",
        estimatedMinutes: 42,
        topics: ["tvpi", "dpi", "rvpi", "performance-measurement"],
        difficulty: "intermediate",
        prerequisites: ["day-04"],
        learningObjectives: [
          "Define TVPI, DPI, and RVPI",
          "Understand how they relate to each other",
          "Use multiples alongside IRR for a complete picture",
        ],
      },
      {
        lessonId: "day-06",
        dayNumber: 6,
        title: "Fund Life Cycles and Vintage Years",
        estimatedMinutes: 38,
        topics: ["fund-lifecycle", "vintage-year", "benchmarking"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-03"],
        learningObjectives: [
          "Interpret any PE fund's metrics correctly by lifecycle phase",
          "Explain why vintage year is the primary benchmarking axis",
          "Construct a valid vintage-adjusted peer group comparison",
          "Identify what metrics are informative at each lifecycle stage",
        ],
      },
      {
        lessonId: "day-07",
        dayNumber: 7,
        title: "Buyout Strategy Fundamentals",
        estimatedMinutes: 43,
        topics: ["buyout", "leverage", "deal-structure", "return-attribution"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-02"],
        learningObjectives: [
          "Apply the five deal selection criteria for buyout targets",
          "Explain capital structure design and leverage amplification arithmetic",
          "Decompose LBO returns into the three-driver value bridge",
          "Interrogate a GP's value creation claims using deal-level attribution",
        ],
      },
      {
        lessonId: "day-08",
        dayNumber: 8,
        title: "Growth Equity vs. Buyout vs. Venture",
        estimatedMinutes: 42,
        topics: ["growth-equity", "buyout", "venture", "portfolio-construction", "strategy-drift"],
        difficulty: "intermediate",
        prerequisites: ["day-07"],
        learningObjectives: [
          "Compare buyout, growth equity, and VC across six analytical dimensions",
          "Explain the portfolio construction role of each sub-strategy",
          "Recognize strategy drift before it becomes a governance problem",
          "Apply sub-strategy-appropriate benchmarks and J-curve expectations",
        ],
      },
      {
        lessonId: "day-09",
        dayNumber: 9,
        title: "Value Creation in PE Portfolio Companies",
        estimatedMinutes: 45,
        topics: ["value-creation", "operations", "portfolio-companies", "return-attribution"],
        difficulty: "intermediate",
        prerequisites: ["day-07"],
        learningObjectives: [
          "Distinguish the four forms of EBITDA growth and their repeatability",
          "Audit a GP's operational value creation claim using portfolio-level data",
          "Identify red flags in value creation presentations",
          "Assess operating partner substance versus marketing",
        ],
      },
      {
        lessonId: "day-10",
        dayNumber: 10,
        title: "Exit Paths: Trade Sales, IPOs, and Secondaries",
        estimatedMinutes: 42,
        topics: ["exits", "ipo", "secondary-buyout", "irr-moic-tradeoff"],
        difficulty: "intermediate",
        prerequisites: ["day-07", "day-09"],
        learningObjectives: [
          "Explain the mechanics and valuation dynamics of each exit route",
          "Quantify the IRR/MOIC trade-off in exit timing decisions",
          "Read secondary buyout patterns as a portfolio quality signal",
          "Analyze a GP's historical exit pattern as a diligence input",
        ],
      },
      {
        lessonId: "day-11",
        dayNumber: 11,
        title: "Distribution Waterfalls and LPA Economics",
        estimatedMinutes: 35,
        topics: ["waterfall", "carry", "lpa", "fee-mechanics", "clawback"],
        difficulty: "advanced",
        prerequisites: ["day-02"],
        learningObjectives: [
          "Construct an American and European waterfall step-by-step and calculate LP and GP distributions at each tier",
          "Compute catch-up mechanics and show how catch-up rate changes total GP carry",
          "Calculate a clawback obligation given a mixed-exit scenario where early wins exceed aggregate fund profit",
          "Quantify the LP economic impact of fee-offset rates at realistic fund scale",
        ],
      },
      {
        lessonId: "day-12",
        dayNumber: 12,
        title: "PME and the Benchmarking Toolkit",
        estimatedMinutes: 35,
        topics: ["pme", "benchmarking", "performance-measurement", "direct-alpha", "subscription-line"],
        difficulty: "advanced",
        prerequisites: ["day-04", "day-05", "day-06"],
        learningObjectives: [
          "Calculate KS-PME for a fund given a cashflow schedule and index returns",
          "Distinguish KS-PME, mPME, and Direct Alpha and select the appropriate variant for a given analysis",
          "Identify the three structural ways peer-quartile benchmarks mislead and how to correct for each",
          "Quantify how subscription line credit facilities inflate reported IRR and apply the ILPA guidance on fund-level return reporting",
          "Interpret a GP's benchmark presentation and identify what they are not showing",
        ],
      },
      {
        lessonId: "day-13",
        dayNumber: 13,
        title: "Manager Selection and GP Underwriting",
        estimatedMinutes: 30,
        topics: ["manager-selection", "due-diligence", "track-record", "gp-underwriting"],
        difficulty: "advanced",
        prerequisites: ["day-04", "day-05", "day-11", "day-12"],
        learningObjectives: [
          "Apply a four-dimension evaluation framework to a PE manager and identify where each dimension can be gamed",
          "Decompose a fund track record into deal-level attribution and distinguish concentrated from broad-based returns",
          "Recognize strategy drift, fund-size creep, and team continuity risk as leading indicators before they show in performance data",
          "Frame the five manager-meeting questions that a prepared LP asks and an unprepared one does not",
        ],
      },
      {
        lessonId: "day-14",
        dayNumber: 14,
        title: "Portfolio Construction and Commitment Pacing",
        estimatedMinutes: 35,
        topics: ["pacing", "portfolio-construction", "vintage-diversification", "over-commitment"],
        difficulty: "advanced",
        prerequisites: ["day-06", "day-13"],
        learningObjectives: [
          "Build a pacing model that projects forward PE NAV and annual commitment requirements for a target allocation",
          "Calculate the over-commitment ratio required to maintain a target allocation given typical drawdown and distribution rates",
          "Manage vintage-year concentration risk across a multi-fund PE programme",
          "Identify when a pacing model's assumptions are stale and what forces a recalibration",
        ],
      },
      {
        lessonId: "day-15",
        dayNumber: 15,
        title: "Secondaries: LP-Led, GP-Led, and Continuation Vehicles",
        estimatedMinutes: 32,
        topics: ["secondary", "lp-led", "gp-led", "continuation-vehicle", "nav-financing"],
        difficulty: "advanced",
        prerequisites: ["day-10", "day-14"],
        learningObjectives: [
          "Explain the pricing mechanics of an LP-led secondary and the factors that widen or narrow the discount to NAV",
          "Identify the structural conflicts in a GP-led secondary and the governance protections that mitigate them",
          "Evaluate a continuation vehicle as an LP decision: roll, sell, or decline, and what information is required for each",
          "Distinguish a secondary market transaction from a secondary buyout exit (Day 10) and explain why the distinction matters in a meeting",
        ],
      },
      {
        lessonId: "day-16",
        dayNumber: 16,
        title: "Co-investments: Economics and Adverse Selection",
        estimatedMinutes: 30,
        topics: ["co-investment", "adverse-selection", "fee-economics", "concentration-risk"],
        difficulty: "advanced",
        prerequisites: ["day-07", "day-12"],
        learningObjectives: [
          "Calculate the net return impact of zero-fee co-invest alongside a fund position at realistic economics",
          "Identify the four adverse selection signals that indicate a co-invest deserves harder scrutiny",
          "Assess portfolio-level concentration risk created by fund exposure plus direct co-invest in the same company",
          "Build a co-invest programme policy that captures fee benefits while managing adverse selection and underwriting capacity",
        ],
      },
      {
        lessonId: "day-17",
        dayNumber: 17,
        title: "Reporting, NAV, and Mark Integrity",
        estimatedMinutes: 32,
        topics: ["nav", "reporting", "valuation", "asc-820", "mark-management"],
        difficulty: "advanced",
        prerequisites: ["day-05", "day-09", "day-12"],
        learningObjectives: [
          "Explain the ASC 820 Level 3 valuation process and the judgment points where GP marks can credibly diverge",
          "Quantify the smoothing effect on reported volatility and correlation and explain why it is a measurement artefact, not a portfolio benefit",
          "Use exit-multiple-surprise analysis across a GP's prior exits to assess whether they mark conservatively or aggressively",
          "Construct the LP call questions that stress-test whether current interim NAV marks are credible",
        ],
      },
      {
        lessonId: "day-18",
        dayNumber: 18,
        title: "PE in the Portfolio: Allocation and the Illiquidity Premium",
        estimatedMinutes: 30,
        topics: ["asset-allocation", "illiquidity-premium", "portfolio-theory", "liquidity-budget"],
        difficulty: "advanced",
        prerequisites: ["day-14", "day-17"],
        learningObjectives: [
          "Assess the empirical evidence for a PE illiquidity premium and the conditions under which it is and is not earned",
          "Size a PE allocation against three binding constraints: liquidity budget, governance capacity, and return objective",
          "Compare PE allocation frameworks across endowment, pension, and OCIO contexts with different liability structures",
          "Apply a PME-based return hurdle to evaluate whether a proposed allocation increase is justified",
        ],
      },
      {
        lessonId: "day-19",
        dayNumber: 19,
        title: "GP Governance, ESG, and Ongoing LP Oversight",
        estimatedMinutes: 30,
        topics: ["governance", "esg", "impact", "lp-oversight", "regulation", "lpac"],
        difficulty: "advanced",
        prerequisites: ["day-11", "day-12"],
        learningObjectives: [
          "Identify GP conflicts of interest that arise post-commitment and the LPAC mechanisms that address them",
          "Distinguish substantive ESG integration from marketing language and apply a deal-level diligence test",
          "Explain the SFDR Article 8 and 9 classification framework and its practical implications for GP reporting",
          "Build an ongoing monitoring framework covering reporting cadence, red-flag triggers, and escalation paths",
        ],
      },
      {
        lessonId: "day-20",
        dayNumber: 20,
        title: "Capstone: Manager Meeting Simulation",
        estimatedMinutes: 30,
        topics: ["synthesis", "meeting-fluency", "allocator-thinking", "diligence-judgment"],
        difficulty: "advanced",
        prerequisites: ["day-15", "day-16", "day-17", "day-18", "day-19"],
        learningObjectives: [
          "Analyze a realistic GP presentation and identify what the numbers confirm, what they obscure, and what is missing",
          "Integrate performance metrics, team signals, LPA terms, and portfolio construction context into a single investment judgment",
          "Draft a diligence-quality commit-or-pass recommendation that explicitly names the two strongest signals and the two most important unresolved risks",
          "Recognize the five most common ways a PE manager presents strong-looking data that obscures weak fundamentals",
        ],
      },
      // ── Days 21–26: LP Operations & Fund Governance ────────────────────────
      {
        lessonId: "day-21",
        dayNumber: 21,
        title: "Fund Documentation Literacy (LPA, Side Letters, MFN)",
        estimatedMinutes: 38,
        topics: ["lpa", "side-letters", "mfn", "fund-documentation", "lp-rights"],
        difficulty: "advanced",
        prerequisites: ["day-02", "day-11"],
        learningObjectives: [
          "Identify the LPA provisions that most directly affect LP economics, governance rights, and flexibility",
          "Explain the purpose and mechanics of side letters and most-favoured-nation clauses",
          "Recognize the documentation gaps that expose LPs to unforeseen economic or governance risk",
        ],
      },
      {
        lessonId: "day-22",
        dayNumber: 22,
        title: "Governance and Conflicts in Practice (LPAC, Valuations, GP-Led Actions)",
        estimatedMinutes: 35,
        topics: ["lpac", "governance", "conflicts-of-interest", "gp-led", "valuation-committee"],
        difficulty: "advanced",
        prerequisites: ["day-11", "day-21"],
        learningObjectives: [
          "Explain how LPACs function and the categories of conflicts they are designed to catch",
          "Understand how valuation committees and GP-led transaction approvals interact with LP governance",
          "Assess whether LPAC representation provides substantive protection or cosmetic oversight",
        ],
      },
      {
        lessonId: "day-23",
        dayNumber: 23,
        title: "Reporting and Data Quality (ILPA Templates as Allocator Infrastructure)",
        estimatedMinutes: 32,
        topics: ["ilpa", "reporting", "data-quality", "portfolio-monitoring", "standardization"],
        difficulty: "advanced",
        prerequisites: ["day-05", "day-12", "day-21"],
        learningObjectives: [
          "Explain the ILPA Reporting Template standard and what it enables for portfolio-level aggregation",
          "Identify the data quality failures that make cross-GP comparison unreliable",
          "Build an allocator data infrastructure that supports multi-manager analytical discipline",
        ],
      },
      {
        lessonId: "day-24",
        dayNumber: 24,
        title: "Valuation Governance for Private Assets (IPEV, ASC 820, Mark Credibility)",
        estimatedMinutes: 35,
        topics: ["ipev", "asc-820", "valuation-governance", "mark-credibility", "independent-valuation"],
        difficulty: "advanced",
        prerequisites: ["day-05", "day-17"],
        learningObjectives: [
          "Explain the IPEV and ASC 820 frameworks and the governance structures that produce credible interim marks",
          "Distinguish valuation methodology from valuation judgment",
          "Evaluate whether a GP's valuation process and exit-surprise history support or undermine mark credibility",
        ],
      },
      {
        lessonId: "day-25",
        dayNumber: 25,
        title: "Fund Finance Beyond Subscription Lines (NAV Facilities and Implications)",
        estimatedMinutes: 35,
        topics: ["nav-facility", "fund-finance", "leverage", "dpi-manufacturing", "lp-risk"],
        difficulty: "advanced",
        prerequisites: ["day-03", "day-11", "day-21"],
        learningObjectives: [
          "Explain NAV-based credit facilities — how they are structured and why GPs use them",
          "Distinguish subscription lines from NAV facilities in economic and governance terms",
          "Identify how NAV facilities can manufacture DPI without realizing value and adjust performance analysis accordingly",
        ],
      },
      {
        lessonId: "day-26",
        dayNumber: 26,
        title: "Liquidity and Commitment Management Across a Multi-Sleeve Program",
        estimatedMinutes: 38,
        topics: ["liquidity-management", "commitment-pacing", "secondary-optionality", "liquidity-buffer", "multi-vintage"],
        difficulty: "advanced",
        prerequisites: ["day-03", "day-14", "day-15", "day-25"],
        learningObjectives: [
          "Build a liquidity framework integrating capital call obligations, distribution expectations, and secondary optionality across multiple fund vintages",
          "Quantify the liquidity buffer required to avoid forced selling under stress scenarios",
          "Identify the programme design choices that create versus mitigate forced-sale risk",
        ],
      },
      // ── Days 27–39: Venture Capital & Growth Equity ─────────────────────────
      {
        lessonId: "day-27",
        dayNumber: 27,
        title: "Venture as a Power-Law Game (Return Distributions and Implications)",
        estimatedMinutes: 38,
        topics: ["venture-capital", "power-law", "return-distribution", "portfolio-construction", "vc-benchmarking"],
        difficulty: "intermediate",
        prerequisites: ["day-04", "day-05", "day-08"],
        learningObjectives: [
          "Explain why VC fund returns follow a power-law distribution and the implications for portfolio construction and manager selection",
          "Contrast VC return distributions with buyout return distributions and identify where conventional intuitions break down",
          "Rebuild benchmark interpretation logic around power-law expectations",
        ],
      },
      {
        lessonId: "day-28",
        dayNumber: 28,
        title: "Venture Map and Stage Taxonomy (Seed to Growth; Fund Archetypes)",
        estimatedMinutes: 35,
        topics: ["venture-stages", "seed", "series-a", "growth-stage", "fund-archetypes", "stage-diligence"],
        difficulty: "intermediate",
        prerequisites: ["day-08", "day-27"],
        learningObjectives: [
          "Map the venture ecosystem by stage and fund archetype from pre-seed to late-stage/crossover",
          "Identify the analytical and governance differences between stage categories that matter for allocator diligence",
          "Avoid stage confusion — the single most common allocator error in VC",
        ],
      },
      {
        lessonId: "day-29",
        dayNumber: 29,
        title: "Cap Tables and Ownership Math for Allocators",
        estimatedMinutes: 40,
        topics: ["cap-table", "dilution", "ownership-math", "pro-rata", "lp-economics"],
        difficulty: "intermediate",
        prerequisites: ["day-28"],
        learningObjectives: [
          "Read a cap table and calculate LP ownership, dilution, and economic entitlement through financing rounds",
          "Understand pro rata rights and their portfolio management implications",
          "Assess whether a GP is defending LP economics or allowing dilution to erode it",
        ],
      },
      {
        lessonId: "day-30",
        dayNumber: 30,
        title: "Seed Instruments (SAFEs / Convertibles) and Allocator Implications",
        estimatedMinutes: 38,
        topics: ["safe", "convertible-note", "seed-instruments", "conversion-mechanics", "valuation-cap"],
        difficulty: "intermediate",
        prerequisites: ["day-29"],
        learningObjectives: [
          "Explain SAFE and convertible note mechanics — conversion triggers, valuation caps, and discount rates",
          "Translate seed instrument terms into LP economic impact at conversion",
          "Assess whether a GP negotiated seed terms from strength or defaulted to founder-friendly structures",
        ],
      },
      {
        lessonId: "day-31",
        dayNumber: 31,
        title: "Preferred Terms I (Liquidation Preference and Company-Level Waterfalls)",
        estimatedMinutes: 40,
        topics: ["liquidation-preference", "company-waterfall", "preferred-equity", "exit-scenarios", "lp-recovery"],
        difficulty: "advanced",
        prerequisites: ["day-29", "day-30"],
        learningObjectives: [
          "Construct a company-level distribution waterfall using liquidation preference mechanics",
          "Quantify LP economic outcomes under multiple exit scenarios including below-preference exits",
          "Apply liquidation preference analysis to assess whether reported RVPI is recoverable under stress",
        ],
      },
      {
        lessonId: "day-32",
        dayNumber: 32,
        title: "Preferred Terms II (Anti-Dilution, Pro Rata, Control Rights)",
        estimatedMinutes: 38,
        topics: ["anti-dilution", "broad-based-weighted-average", "full-ratchet", "pro-rata", "control-rights"],
        difficulty: "advanced",
        prerequisites: ["day-31"],
        learningObjectives: [
          "Explain anti-dilution protection mechanics — broad-based weighted average versus full ratchet",
          "Assess pro rata investment rights and information and board control provisions",
          "Identify how preferred terms affect LP outcomes in down rounds and control contests",
        ],
      },
      {
        lessonId: "day-33",
        dayNumber: 33,
        title: "Venture Valuation and Marks (Down Rounds, Structured Rounds, 409A Reality)",
        estimatedMinutes: 38,
        topics: ["vc-valuation", "down-rounds", "structured-rounds", "409a", "mark-inflation"],
        difficulty: "advanced",
        prerequisites: ["day-24", "day-31", "day-32"],
        learningObjectives: [
          "Explain how VC interim marks are set and how structured rounds can mask flat or down performance",
          "Understand how 409A appraisals relate to LP-reported NAV",
          "Identify the mark inflation techniques common in late-stage portfolios",
        ],
      },
      {
        lessonId: "day-34",
        dayNumber: 34,
        title: "Venture Underwriting by Business Model and Sector",
        estimatedMinutes: 40,
        topics: ["vc-underwriting", "saas", "marketplace", "deep-tech", "consumer", "business-model"],
        difficulty: "advanced",
        prerequisites: ["day-28", "day-29"],
        learningObjectives: [
          "Apply business-model-specific underwriting logic to SaaS, marketplace, deep tech, and consumer categories",
          "Identify the key value-creation assumptions and failure modes specific to each business model",
          "Distinguish specialist underwriting from generic VC frameworks",
        ],
      },
      {
        lessonId: "day-35",
        dayNumber: 35,
        title: "Venture Portfolio Management (Follow-Ons, Reserves, Signaling)",
        estimatedMinutes: 38,
        topics: ["follow-on", "reserve-management", "signaling", "vc-portfolio-management", "fund-returns"],
        difficulty: "advanced",
        prerequisites: ["day-27", "day-29", "day-31"],
        learningObjectives: [
          "Explain GP reserve management mechanics and the follow-on decision framework",
          "Quantify the impact of reserve allocation decisions on fund-level returns",
          "Assess reserve discipline as a signal of VC manager portfolio management skill",
        ],
      },
      {
        lessonId: "day-36",
        dayNumber: 36,
        title: "Venture Exits and Liquidity (IPO, M&A, Tenders, Secondaries)",
        estimatedMinutes: 38,
        topics: ["vc-exits", "ipo-lockup", "tender-offer", "company-secondary", "dpi-timing"],
        difficulty: "advanced",
        prerequisites: ["day-10", "day-35"],
        learningObjectives: [
          "Explain the mechanics and timing dynamics of each VC exit route including IPO lock-up implications",
          "Quantify the LP liquidity and DPI implications of each exit path",
          "Build a distribution policy that accounts for the structural delay in VC DPI relative to buyout",
        ],
      },
      {
        lessonId: "day-37",
        dayNumber: 37,
        title: "Growth Equity: Distinguishing from Venture and Buyout",
        estimatedMinutes: 38,
        topics: ["growth-equity", "growth-equity-underwriting", "minority-growth", "growth-vs-buyout", "growth-vs-venture"],
        difficulty: "advanced",
        prerequisites: ["day-27", "day-28", "day-36"],
        learningObjectives: [
          "Distinguish growth equity from both venture and buyout on risk profile, ownership structure, and return expectations",
          "Apply growth-equity-specific underwriting criteria including revenue quality, growth sustainability, and unit economics",
          "Evaluate growth equity managers using criteria appropriate to the strategy rather than borrowed VC or buyout frameworks",
        ],
      },
      {
        lessonId: "day-38",
        dayNumber: 38,
        title: "Late-Stage and Crossover Dynamics",
        estimatedMinutes: 38,
        topics: ["crossover-funds", "late-stage-private", "ipo-readiness", "mark-inflation", "crossover-dynamics"],
        difficulty: "advanced",
        prerequisites: ["day-33", "day-36", "day-37"],
        learningObjectives: [
          "Explain how crossover investors participate in late-stage private rounds and how their presence affects valuations and cap tables",
          "Assess the risks of crossover-inflated marks and how public market corrections flow back into private portfolios",
          "Evaluate IPO readiness and the transition from late-stage private to public as a distinct allocator judgment",
        ],
      },
      {
        lessonId: "day-39",
        dayNumber: 39,
        title: "Venture Manager Evaluation as Allocator Discipline",
        estimatedMinutes: 42,
        topics: ["vc-manager-evaluation", "manager-selection", "gp-underwriting", "venture-edge", "sourcing-selection"],
        difficulty: "advanced",
        prerequisites: ["day-27", "day-36", "day-37", "day-38"],
        learningObjectives: [
          "Apply a systematic framework to evaluate venture manager edge across sourcing, selection, ownership, reserves, value-add, and monetization",
          "Distinguish real venture edge from brand inertia and polished storytelling using ownership outcomes and reserve behavior as tests",
          "Assess partnership durability, succession risk, and the difference between firm brand and the actual decision engine driving returns",
        ],
      },
    ],
  },
];

export function getModuleById(moduleId: string): Module | undefined {
  return modules.find((m) => m.moduleId === moduleId);
}

/** The default module used when no explicit module is specified. */
export const DEFAULT_MODULE_ID = "pe-foundations";

/** Convenience: get the default module. */
export function getDefaultModule(): Module {
  const m = getModuleById(DEFAULT_MODULE_ID);
  if (!m) throw new Error(`Default module "${DEFAULT_MODULE_ID}" not found`);
  return m;
}
