import { Module } from "./types";

export const modules: Module[] = [
  {
    moduleId: "pe-foundations",
    moduleTitle: "Private Equity Foundations",
    description:
      "A 20-day curriculum building PE fluency from fund structure to portfolio construction. Designed for CFA charterholders with public-markets backgrounds.",
    lessons: [
      {
        lessonId: "day-01",
        dayNumber: 1,
        title: "How Private Equity Actually Works",
        estimatedMinutes: 45,
        topics: ["pe-basics", "fund-structure", "capital-flow"],
        difficulty: "foundational",
        prerequisites: [],
        learningObjectives: [
          "Explain the basic PE fund model in plain English",
          "Understand how capital is called, invested, harvested, and distributed",
          "Distinguish GP-level claims from fund-structure mechanics",
        ],
      },
      {
        lessonId: "day-02",
        dayNumber: 2,
        title: "GPs, LPs, and the Incentive Stack",
        estimatedMinutes: 43,
        topics: ["gp-lp", "incentives", "carried-interest"],
        difficulty: "foundational",
        prerequisites: ["day-01"],
        learningObjectives: [
          "Understand the GP/LP relationship",
          "Explain management fees and carried interest",
          "Describe how incentive alignment works in PE",
        ],
      },
      {
        lessonId: "day-03",
        dayNumber: 3,
        title: "Capital Calls and the J-Curve",
        estimatedMinutes: 40,
        topics: ["capital-calls", "j-curve", "cash-flows"],
        difficulty: "foundational",
        prerequisites: ["day-01", "day-02"],
        learningObjectives: [
          "Explain the capital call mechanism",
          "Understand the J-curve and why it happens",
          "Anticipate liquidity implications for LPs",
        ],
      },
      {
        lessonId: "day-04",
        dayNumber: 4,
        title: "IRR: What It Measures and Where It Breaks",
        estimatedMinutes: 48,
        topics: ["irr", "performance-measurement"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-03"],
        learningObjectives: [
          "Calculate and interpret IRR",
          "Identify where IRR is gamed or misleading",
          "Distinguish gross from net IRR",
        ],
      },
      {
        lessonId: "day-05",
        dayNumber: 5,
        title: "TVPI, DPI, and RVPI Explained",
        estimatedMinutes: 42,
        topics: ["tvpi", "dpi", "rvpi", "performance-measurement"],
        difficulty: "intermediate",
        prerequisites: ["day-04"],
        learningObjectives: [
          "Define TVPI, DPI, and RVPI",
          "Understand how they relate to each other",
          "Use multiples alongside IRR for a complete picture",
        ],
      },
      {
        lessonId: "day-06",
        dayNumber: 6,
        title: "Fund Life Cycles and Vintage Years",
        estimatedMinutes: 38,
        topics: ["fund-lifecycle", "vintage-year", "benchmarking"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-03"],
        learningObjectives: [
          "Interpret any PE fund's metrics correctly by lifecycle phase",
          "Explain why vintage year is the primary benchmarking axis",
          "Construct a valid vintage-adjusted peer group comparison",
          "Identify what metrics are informative at each lifecycle stage",
        ],
      },
      {
        lessonId: "day-07",
        dayNumber: 7,
        title: "Buyout Strategy Fundamentals",
        estimatedMinutes: 43,
        topics: ["buyout", "leverage", "deal-structure", "return-attribution"],
        difficulty: "intermediate",
        prerequisites: ["day-01", "day-02"],
        learningObjectives: [
          "Apply the five deal selection criteria for buyout targets",
          "Explain capital structure design and leverage amplification arithmetic",
          "Decompose LBO returns into the three-driver value bridge",
          "Interrogate a GP's value creation claims using deal-level attribution",
        ],
      },
      {
        lessonId: "day-08",
        dayNumber: 8,
        title: "Growth Equity vs. Buyout vs. Venture",
        estimatedMinutes: 42,
        topics: ["growth-equity", "buyout", "venture", "portfolio-construction", "strategy-drift"],
        difficulty: "intermediate",
        prerequisites: ["day-07"],
        learningObjectives: [
          "Compare buyout, growth equity, and VC across six analytical dimensions",
          "Explain the portfolio construction role of each sub-strategy",
          "Recognize strategy drift before it becomes a governance problem",
          "Apply sub-strategy-appropriate benchmarks and J-curve expectations",
        ],
      },
      {
        lessonId: "day-09",
        dayNumber: 9,
        title: "Value Creation in PE Portfolio Companies",
        estimatedMinutes: 45,
        topics: ["value-creation", "operations", "portfolio-companies", "return-attribution"],
        difficulty: "intermediate",
        prerequisites: ["day-07"],
        learningObjectives: [
          "Distinguish the four forms of EBITDA growth and their repeatability",
          "Audit a GP's operational value creation claim using portfolio-level data",
          "Identify red flags in value creation presentations",
          "Assess operating partner substance versus marketing",
        ],
      },
      {
        lessonId: "day-10",
        dayNumber: 10,
        title: "Exit Paths: Trade Sales, IPOs, and Secondaries",
        estimatedMinutes: 42,
        topics: ["exits", "ipo", "secondary-buyout", "irr-moic-tradeoff"],
        difficulty: "intermediate",
        prerequisites: ["day-07", "day-09"],
        learningObjectives: [
          "Explain the mechanics and valuation dynamics of each exit route",
          "Quantify the IRR/MOIC trade-off in exit timing decisions",
          "Read secondary buyout patterns as a portfolio quality signal",
          "Analyze a GP's historical exit pattern as a diligence input",
        ],
      },
      {
        lessonId: "day-11",
        dayNumber: 11,
        title: "Distribution Waterfalls and LPA Economics",
        estimatedMinutes: 35,
        topics: ["waterfall", "carry", "lpa", "fee-mechanics", "clawback"],
        difficulty: "advanced",
        prerequisites: ["day-02"],
        learningObjectives: [
          "Construct an American and European waterfall step-by-step and calculate LP and GP distributions at each tier",
          "Compute catch-up mechanics and show how catch-up rate changes total GP carry",
          "Calculate a clawback obligation given a mixed-exit scenario where early wins exceed aggregate fund profit",
          "Quantify the LP economic impact of fee-offset rates at realistic fund scale",
        ],
      },
      {
        lessonId: "day-12",
        dayNumber: 12,
        title: "PME and the Benchmarking Toolkit",
        estimatedMinutes: 35,
        topics: ["pme", "benchmarking", "performance-measurement", "direct-alpha", "subscription-line"],
        difficulty: "advanced",
        prerequisites: ["day-04", "day-05", "day-06"],
        learningObjectives: [
          "Calculate KS-PME for a fund given a cashflow schedule and index returns",
          "Distinguish KS-PME, mPME, and Direct Alpha and select the appropriate variant for a given analysis",
          "Identify the three structural ways peer-quartile benchmarks mislead and how to correct for each",
          "Quantify how subscription line credit facilities inflate reported IRR and apply the ILPA guidance on fund-level return reporting",
          "Interpret a GP's benchmark presentation and identify what they are not showing",
        ],
      },
      {
        lessonId: "day-13",
        dayNumber: 13,
        title: "Manager Selection and GP Underwriting",
        estimatedMinutes: 30,
        topics: ["manager-selection", "due-diligence", "track-record", "gp-underwriting"],
        difficulty: "advanced",
        prerequisites: ["day-04", "day-05", "day-11", "day-12"],
        learningObjectives: [
          "Apply a four-dimension evaluation framework to a PE manager and identify where each dimension can be gamed",
          "Decompose a fund track record into deal-level attribution and distinguish concentrated from broad-based returns",
          "Recognize strategy drift, fund-size creep, and team continuity risk as leading indicators before they show in performance data",
          "Frame the five manager-meeting questions that a prepared LP asks and an unprepared one does not",
        ],
      },
      {
        lessonId: "day-14",
        dayNumber: 14,
        title: "Portfolio Construction and Commitment Pacing",
        estimatedMinutes: 35,
        topics: ["pacing", "portfolio-construction", "vintage-diversification", "over-commitment"],
        difficulty: "advanced",
        prerequisites: ["day-06", "day-13"],
        learningObjectives: [
          "Build a pacing model that projects forward PE NAV and annual commitment requirements for a target allocation",
          "Calculate the over-commitment ratio required to maintain a target allocation given typical drawdown and distribution rates",
          "Manage vintage-year concentration risk across a multi-fund PE programme",
          "Identify when a pacing model's assumptions are stale and what forces a recalibration",
        ],
      },
      {
        lessonId: "day-15",
        dayNumber: 15,
        title: "Secondaries: LP-Led, GP-Led, and Continuation Vehicles",
        estimatedMinutes: 32,
        topics: ["secondary", "lp-led", "gp-led", "continuation-vehicle", "nav-financing"],
        difficulty: "advanced",
        prerequisites: ["day-10", "day-14"],
        learningObjectives: [
          "Explain the pricing mechanics of an LP-led secondary and the factors that widen or narrow the discount to NAV",
          "Identify the structural conflicts in a GP-led secondary and the governance protections that mitigate them",
          "Evaluate a continuation vehicle as an LP decision: roll, sell, or decline, and what information is required for each",
          "Distinguish a secondary market transaction from a secondary buyout exit (Day 10) and explain why the distinction matters in a meeting",
        ],
      },
      {
        lessonId: "day-16",
        dayNumber: 16,
        title: "Co-investments: Economics and Adverse Selection",
        estimatedMinutes: 30,
        topics: ["co-investment", "adverse-selection", "fee-economics", "concentration-risk"],
        difficulty: "advanced",
        prerequisites: ["day-07", "day-12"],
        learningObjectives: [
          "Calculate the net return impact of zero-fee co-invest alongside a fund position at realistic economics",
          "Identify the four adverse selection signals that indicate a co-invest deserves harder scrutiny",
          "Assess portfolio-level concentration risk created by fund exposure plus direct co-invest in the same company",
          "Build a co-invest programme policy that captures fee benefits while managing adverse selection and underwriting capacity",
        ],
      },
      {
        lessonId: "day-17",
        dayNumber: 17,
        title: "Reporting, NAV, and Mark Integrity",
        estimatedMinutes: 32,
        topics: ["nav", "reporting", "valuation", "asc-820", "mark-management"],
        difficulty: "advanced",
        prerequisites: ["day-05", "day-09", "day-12"],
        learningObjectives: [
          "Explain the ASC 820 Level 3 valuation process and the judgment points where GP marks can credibly diverge",
          "Quantify the smoothing effect on reported volatility and correlation and explain why it is a measurement artefact, not a portfolio benefit",
          "Use exit-multiple-surprise analysis across a GP's prior exits to assess whether they mark conservatively or aggressively",
          "Construct the LP call questions that stress-test whether current interim NAV marks are credible",
        ],
      },
      {
        lessonId: "day-18",
        dayNumber: 18,
        title: "PE in the Portfolio: Allocation and the Illiquidity Premium",
        estimatedMinutes: 30,
        topics: ["asset-allocation", "illiquidity-premium", "portfolio-theory", "liquidity-budget"],
        difficulty: "advanced",
        prerequisites: ["day-14", "day-17"],
        learningObjectives: [
          "Assess the empirical evidence for a PE illiquidity premium and the conditions under which it is and is not earned",
          "Size a PE allocation against three binding constraints: liquidity budget, governance capacity, and return objective",
          "Compare PE allocation frameworks across endowment, pension, and OCIO contexts with different liability structures",
          "Apply a PME-based return hurdle to evaluate whether a proposed allocation increase is justified",
        ],
      },
      {
        lessonId: "day-19",
        dayNumber: 19,
        title: "GP Governance, ESG, and Ongoing LP Oversight",
        estimatedMinutes: 30,
        topics: ["governance", "esg", "impact", "lp-oversight", "regulation", "lpac"],
        difficulty: "advanced",
        prerequisites: ["day-11", "day-12"],
        learningObjectives: [
          "Identify GP conflicts of interest that arise post-commitment and the LPAC mechanisms that address them",
          "Distinguish substantive ESG integration from marketing language and apply a deal-level diligence test",
          "Explain the SFDR Article 8 and 9 classification framework and its practical implications for GP reporting",
          "Build an ongoing monitoring framework covering reporting cadence, red-flag triggers, and escalation paths",
        ],
      },
      {
        lessonId: "day-20",
        dayNumber: 20,
        title: "Capstone: Manager Meeting Simulation",
        estimatedMinutes: 30,
        topics: ["synthesis", "meeting-fluency", "allocator-thinking", "diligence-judgment"],
        difficulty: "advanced",
        prerequisites: ["day-15", "day-16", "day-17", "day-18", "day-19"],
        learningObjectives: [
          "Analyze a realistic GP presentation and identify what the numbers confirm, what they obscure, and what is missing",
          "Integrate performance metrics, team signals, LPA terms, and portfolio construction context into a single investment judgment",
          "Draft a diligence-quality commit-or-pass recommendation that explicitly names the two strongest signals and the two most important unresolved risks",
          "Recognize the five most common ways a PE manager presents strong-looking data that obscures weak fundamentals",
        ],
      },
    ],
  },
];

export function getModuleById(moduleId: string): Module | undefined {
  return modules.find((m) => m.moduleId === moduleId);
}

/** The default module used when no explicit module is specified. */
export const DEFAULT_MODULE_ID = "pe-foundations";

/** Convenience: get the default module. */
export function getDefaultModule(): Module {
  const m = getModuleById(DEFAULT_MODULE_ID);
  if (!m) throw new Error(`Default module "${DEFAULT_MODULE_ID}" not found`);
  return m;
}
