import { ReviewCard } from "./types";

// One or two cards per lesson — mix of flashcard / mini-case / reteach
export const allReviewCards: ReviewCard[] = [
  // Day 1
  {
    cardId: "d01-fc1",
    lessonId: "day-01",
    dayNumber: 1,
    cardType: "flashcard",
    topic: "fund-structure",
    front: "What is a closed-end PE fund?",
    back: "A vehicle where LPs commit capital upfront, the GP draws it down over the investment period, deploys it into companies, and distributes proceeds as exits occur — typically over a 10-year life.",
  },
  {
    cardId: "d01-rt1",
    lessonId: "day-01",
    dayNumber: 1,
    cardType: "reteach",
    topic: "capital-flow",
    front: "Committed capital ≠ invested capital.",
    back: "LPs pledge a total amount but only transfer cash when the GP issues a capital call. Uninvested committed capital sits at the LP until drawn.",
  },
  // Day 2
  {
    cardId: "d02-fc1",
    lessonId: "day-02",
    dayNumber: 2,
    cardType: "flashcard",
    topic: "carried-interest",
    front: "What is carried interest and the typical rate?",
    back: "The GP's share of fund profits above the hurdle rate — conventionally 20%. It aligns GP incentives with LP returns but only pays after LPs recover their capital plus hurdle.",
  },
  {
    cardId: "d02-mc1",
    lessonId: "day-02",
    dayNumber: 2,
    cardType: "mini-case",
    topic: "incentives",
    front: "A GP earns a 2% management fee on a $1B fund. After year 5, committed capital steps down to invested capital ($600M). How does the annual fee change?",
    back: "Fee drops from $20M/yr to $12M/yr. This step-down is standard and aligns GP incentives with deployment rather than AUM accumulation.",
  },
  // Day 3
  {
    cardId: "d03-fc1",
    lessonId: "day-03",
    dayNumber: 3,
    cardType: "flashcard",
    topic: "j-curve",
    front: "Why does a PE fund's IRR go negative in early years?",
    back: "Fees and early writedowns hit before exits generate returns — creating the J-curve. Interim IRRs are unreliable until the fund is at least 60–70% through its life.",
  },
  {
    cardId: "d03-rt1",
    lessonId: "day-03",
    dayNumber: 3,
    cardType: "reteach",
    topic: "capital-calls",
    front: "Capital calls are not predictable in timing.",
    back: "GPs issue calls when deals close, not on a fixed schedule. LPs must maintain liquid reserves to fund calls on short notice — typically 10 business days.",
  },
  // Day 4
  {
    cardId: "d04-fc1",
    lessonId: "day-04",
    dayNumber: 4,
    cardType: "flashcard",
    topic: "irr",
    front: "What does IRR measure in a PE context?",
    back: "The annualised return that makes NPV of all cash flows (calls and distributions) equal to zero. It is time-weighted for cash timing, not capital size.",
  },
  {
    cardId: "d04-mc1",
    lessonId: "day-04",
    dayNumber: 4,
    cardType: "mini-case",
    topic: "irr",
    front: "Two funds report 25% gross IRR. Fund A invested $500M; Fund B invested $50M. How should you compare them?",
    back: "IRR alone is misleading at different scales. Fund A generated far more absolute dollar profit. Use TVPI/DPI alongside IRR, and consider PME to benchmark against public markets.",
  },
  // Day 5
  {
    cardId: "d05-fc1",
    lessonId: "day-05",
    dayNumber: 5,
    cardType: "flashcard",
    topic: "dpi",
    front: "What does DPI measure and why does it matter more than TVPI late in a fund's life?",
    back: "DPI (Distributions to Paid-In) measures realized returns only. Late in fund life, unrealized NAV should be small — if DPI is still low, the fund has not actually returned capital.",
  },
  {
    cardId: "d05-rt1",
    lessonId: "day-05",
    dayNumber: 5,
    cardType: "reteach",
    topic: "rvpi",
    front: "RVPI = residual NAV / paid-in capital.",
    back: "It represents the unrealized portion of the portfolio. High RVPI late in fund life is a red flag — it suggests the GP is sitting on marks rather than returning capital.",
  },
  // Day 6
  {
    cardId: "d06-fc1",
    lessonId: "day-06",
    dayNumber: 6,
    cardType: "flashcard",
    topic: "vintage-year",
    front: "Why does vintage year matter when benchmarking PE performance?",
    back: "Funds raised in the same vintage face the same macro and credit cycle. Comparing a 2009 vintage (buying cheap post-GFC) to a 2007 vintage (buying at peak) is apples to oranges.",
  },
  // Day 7
  {
    cardId: "d07-fc1",
    lessonId: "day-07",
    dayNumber: 7,
    cardType: "flashcard",
    topic: "buyout",
    front: "What are the three main return drivers in a leveraged buyout?",
    back: "1) Earnings growth (EBITDA expansion), 2) Multiple expansion (exit at a higher EV/EBITDA than entry), 3) Leverage paydown (debt reduction increases equity value). The best deals combine all three.",
  },
  {
    cardId: "d07-mc1",
    lessonId: "day-07",
    dayNumber: 7,
    cardType: "mini-case",
    topic: "leverage",
    front: "A GP buys a company at 8x EBITDA with 60% debt. EBITDA grows 30% over 5 years and exits at 10x. What drove most of the return?",
    back: "Multiple expansion (8x → 10x) and earnings growth both contributed. At 60% initial leverage, debt paydown also meaningfully increased equity value. Decomposing these three buckets is standard in LP due diligence.",
  },
  // Day 8
  {
    cardId: "d08-fc1",
    lessonId: "day-08",
    dayNumber: 8,
    cardType: "flashcard",
    topic: "growth-equity",
    front: "How does growth equity differ from buyout in risk/return profile?",
    back: "Growth equity uses little or no leverage, takes minority stakes in high-growth companies, and relies almost entirely on earnings growth for returns. Lower leverage = less downside amplification but also less upside from financial engineering.",
  },
  // Day 9
  {
    cardId: "d09-rt1",
    lessonId: "day-09",
    dayNumber: 9,
    cardType: "reteach",
    topic: "value-creation",
    front: "PE value creation = operational improvement + financial engineering + multiple expansion.",
    back: "Top-quartile GPs lead on operational improvements (revenue growth, margin expansion, bolt-on acquisitions). Reliance on multiple expansion or leverage alone is not repeatable alpha.",
  },
  {
    cardId: "d09-mc1",
    lessonId: "day-09",
    dayNumber: 9,
    cardType: "mini-case",
    topic: "operations",
    front: "A GP claims 'operational value creation' but all portfolio companies saw EBITDA margins decline while multiples expanded. How do you assess this?",
    back: "The GP's narrative is not supported by the data. Multiple expansion drove returns here. Ask for a value-bridge showing the contribution of revenue growth, margin improvement, and multiple change separately across the portfolio.",
  },
  // Day 10
  {
    cardId: "d10-fc1",
    lessonId: "day-10",
    dayNumber: 10,
    cardType: "flashcard",
    topic: "exits",
    front: "What are the three main PE exit routes?",
    back: "1) Trade sale (sell to a strategic buyer), 2) Secondary buyout (sell to another PE firm), 3) IPO. Trade sales typically yield the highest multiples; IPOs provide liquidity but expose timing risk.",
  },
  // Day 11
  {
    cardId: "d11-fc1",
    lessonId: "day-11",
    dayNumber: 11,
    cardType: "flashcard",
    topic: "lpa",
    front: "What is a key man clause in an LPA?",
    back: "A provision that suspends or terminates the investment period if specific named partners leave the GP. It protects LPs from the fund continuing under materially different leadership than what they committed to.",
  },
  {
    cardId: "d11-rt1",
    lessonId: "day-11",
    dayNumber: 11,
    cardType: "reteach",
    topic: "fund-terms",
    front: "The hurdle rate is not guaranteed — it is a preferential return threshold.",
    back: "LPs receive distributions first until they recover capital plus the hurdle (usually 8%). Only then does carry kick in. But if deals underperform, LPs may not hit the hurdle and the GP earns no carry.",
  },
  // Day 12
  {
    cardId: "d12-mc1",
    lessonId: "day-12",
    dayNumber: 12,
    cardType: "mini-case",
    topic: "manager-selection",
    front: "A GP shows top-quartile IRR across three funds. The lead partner recently retired and the team has turned over 40% in two years. Do you re-up?",
    back: "This is a classic key-person risk situation. Past performance was likely tied to the departed partner. Re-underwrite the team independently. The track record may not transfer. Most institutions would require a smaller commitment or pass.",
  },
  {
    cardId: "d12-fc1",
    lessonId: "day-12",
    dayNumber: 12,
    cardType: "flashcard",
    topic: "due-diligence",
    front: "What is 'attribution analysis' in PE due diligence?",
    back: "Breaking down a fund's returns into deal-level contributors — identifying which deals drove performance, whether wins were concentrated, and whether the GP repeated a consistent strategy or got lucky on one outlier.",
  },
  // Day 13
  {
    cardId: "d13-fc1",
    lessonId: "day-13",
    dayNumber: 13,
    cardType: "flashcard",
    topic: "pme",
    front: "What does PME (Public Market Equivalent) measure?",
    back: "PME benchmarks PE returns against a hypothetical public-market investment with the same cash flow timing. A PME > 1.0 means the PE fund outperformed the index on a like-for-like basis.",
  },
  // Day 14
  {
    cardId: "d14-fc1",
    lessonId: "day-14",
    dayNumber: 14,
    cardType: "flashcard",
    topic: "pacing",
    front: "What is a PE pacing model?",
    back: "A cash-flow projection tool that models future capital calls and distributions to keep PE allocation near a target. It balances new commitments against expected drawdowns to avoid over- or under-allocation.",
  },
  {
    cardId: "d14-mc1",
    lessonId: "day-14",
    dayNumber: 14,
    cardType: "mini-case",
    topic: "portfolio-construction",
    front: "A $1B endowment targets 20% PE. The current PE NAV is $150M. How do you construct a pacing plan?",
    back: "Target NAV is $200M. With PE funds drawing capital over 3–5 years and returning it over 7–10, you need to commit 2–3x target NAV per cycle. Commit ~$100–150M/yr over 3 years across 3–5 funds to reach and sustain target allocation.",
  },
  // Day 15
  {
    cardId: "d15-fc1",
    lessonId: "day-15",
    dayNumber: 15,
    cardType: "flashcard",
    topic: "secondary",
    front: "What is a GP-led secondary?",
    back: "A transaction where the GP moves one or more portfolio companies into a new continuation vehicle, giving existing LPs the option to cash out or roll in. It extends hold periods on trophy assets but raises conflicts of interest.",
  },
  // Day 16
  {
    cardId: "d16-rt1",
    lessonId: "day-16",
    dayNumber: 16,
    cardType: "reteach",
    topic: "co-investment",
    front: "Co-investments reduce fees but introduce adverse selection risk.",
    back: "GPs offer co-invest on deals that are too large for the fund alone — or sometimes deals they couldn't fully fill in the fund. LPs must assess whether they're getting the best deals or the overflow.",
  },
  // Day 17
  {
    cardId: "d17-fc1",
    lessonId: "day-17",
    dayNumber: 17,
    cardType: "flashcard",
    topic: "asset-allocation",
    front: "What is the illiquidity premium argument for PE?",
    back: "Investors accepting lock-up and illiquidity should earn a premium over public markets. Empirical evidence is mixed — net-of-fee PE returns need to materially exceed public benchmarks to justify the illiquidity cost.",
  },
  // Day 18
  {
    cardId: "d18-fc1",
    lessonId: "day-18",
    dayNumber: 18,
    cardType: "flashcard",
    topic: "nav",
    front: "Why does PE NAV smooth volatility relative to public markets?",
    back: "PE NAV is based on lagged appraisals, not daily market prices. This creates artificially low reported volatility and correlation — a feature that can mislead portfolio risk models.",
  },
  // Day 19
  {
    cardId: "d19-rt1",
    lessonId: "day-19",
    dayNumber: 19,
    cardType: "reteach",
    topic: "esg",
    front: "ESG in PE is primarily a value-creation lens, not just a screening tool.",
    back: "Leading GPs use ESG factors to reduce portfolio company risk, improve governance, and prepare companies for exit to buyers with ESG mandates. It's increasingly embedded in value-creation plans, not just checklist compliance.",
  },
  // Day 20
  {
    cardId: "d20-mc1",
    lessonId: "day-20",
    dayNumber: 20,
    cardType: "mini-case",
    topic: "meeting-fluency",
    front: "In a GP meeting, the manager says their fund delivered '2.3x TVPI and 22% net IRR, top quartile.' What three follow-up questions do you ask?",
    back: "1) What is the DPI — how much has actually been returned? 2) How does PME compare to the relevant public benchmark? 3) Are returns concentrated in one or two deals, or broad-based across the portfolio?",
  },
  {
    cardId: "d20-fc1",
    lessonId: "day-20",
    dayNumber: 20,
    cardType: "flashcard",
    topic: "synthesis",
    front: "Name the five key metrics to demand in any PE manager meeting.",
    back: "1) Net IRR (after fees), 2) TVPI and DPI (scale of return + cash returned), 3) PME vs. relevant benchmark, 4) Attribution (deal-level concentration), 5) Team continuity since inception.",
  },
];
