/** Single source of truth for human-readable topic labels. */
export const TOPIC_LABELS: Record<string, string> = {
  "pe-basics": "PE Basics",
  "fund-structure": "Fund Structure",
  "capital-flow": "Capital Flow",
  "gp-lp": "GP / LP",
  incentives: "Incentives",
  "carried-interest": "Carried Interest",
  "capital-calls": "Capital Calls",
  "j-curve": "J-Curve",
  "cash-flows": "Cash Flows",
  irr: "IRR",
  "performance-measurement": "Performance",
  tvpi: "TVPI",
  dpi: "DPI",
  rvpi: "RVPI",
  "fund-lifecycle": "Fund Lifecycle",
  "vintage-year": "Vintage Year",
  benchmarking: "Benchmarking",
  buyout: "Buyout",
  leverage: "Leverage",
  "deal-structure": "Deal Structure",
  "return-attribution": "Return Attribution",
  "growth-equity": "Growth Equity",
  venture: "Venture",
  "portfolio-construction": "Portfolio Construction",
  "strategy-drift": "Strategy Drift",
  "value-creation": "Value Creation",
  operations: "Operations",
  "portfolio-companies": "Portfolio Cos",
  exits: "Exits",
  ipo: "IPO",
  "secondary-buyout": "Secondary Buyout",
  "irr-moic-tradeoff": "IRR/MOIC Tradeoff",
  waterfall: "Waterfall",
  carry: "Carry",
  lpa: "LPA",
  "fee-mechanics": "Fee Mechanics",
  clawback: "Clawback",
  "fund-terms": "Fund Terms",
  pme: "PME",
  "direct-alpha": "Direct Alpha",
  "subscription-line": "Subscription Line",
  "manager-selection": "Manager Selection",
  "due-diligence": "Due Diligence",
  "gp-underwriting": "GP Underwriting",
  "track-record": "Track Record",
  pacing: "Pacing",
  "vintage-diversification": "Vintage Diversification",
  "over-commitment": "Over-commitment",
  secondary: "Secondaries",
  "lp-led": "LP-Led",
  "gp-led": "GP-Led",
  "continuation-vehicle": "Continuation Vehicle",
  "nav-financing": "NAV Financing",
  "co-investment": "Co-Investment",
  "adverse-selection": "Adverse Selection",
  "fee-economics": "Fee Economics",
  "concentration-risk": "Concentration Risk",
  nav: "NAV",
  reporting: "Reporting",
  valuation: "Valuation",
  "asc-820": "ASC 820",
  "mark-management": "Mark Management",
  "asset-allocation": "Asset Allocation",
  "illiquidity-premium": "Illiquidity Premium",
  "portfolio-theory": "Portfolio Theory",
  "liquidity-budget": "Liquidity Budget",
  governance: "Governance",
  esg: "ESG",
  impact: "Impact",
  "lp-oversight": "LP Oversight",
  regulation: "Regulation",
  lpac: "LPAC",
  synthesis: "Synthesis",
  "meeting-fluency": "Meeting Fluency",
  "allocator-thinking": "Allocator Thinking",
  "diligence-judgment": "Diligence Judgment",
  allocation: "Allocation",
  liquidity: "Liquidity",
};

/** Get a human-readable label for a topic slug. Falls back to title-casing the slug. */
export function topicLabel(t: string): string {
  return TOPIC_LABELS[t] ?? t.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}
